# SPDX-License-Identifier: GPL-2.0

# Makefile for external connector class (extcon) devices
#

obj-$(CONFIG_EXTCON_ASUS)		+= extcon-asus-core.o
extcon-asus-core-objs		+= extcon-asus.o #devres-asus.o
